### ISSUE TITLE
Error migrating millionaires problem secret contract

### ISSUE THREAD

**Issue by lauracw100** [enigmampc/dev-help#34]
From @MasterNodes on Discord:

I've followed this entire guide: https://blog.enigma.co/getting-started-with-enigma-a-front-end-demo-for-dapps-bc694d3d81b9 and I am able to run discovery start and compile the millionare contract but when I launch my react app it just says: "Millionaires' Problem secret contract not yet deployed..."
It's making the connection to the local dev enviornment, but it won't connect to the contract
node v10.16.3
discovery-cli v0.1.3

--------

Error on `discovery migrate`
```
Macs-Air:enigma mac$ discovery migrate (node:49865) UnhandledPromiseRejectionWarning: Error: SyntaxError: await is only valid in async function     at Object.run (/Users/mac/.npm-global/lib/node_modules/@enigmampc/discovery-cli/node_modules/@truffle/migrate/index.js:96:13)     at process._tickCallback (internal/process/next_tick.js:68:7) (node:49865) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1) (node:49865) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I'm going to fork his repo and see if I can get it working for him.

**Comment by lauracw100** [comment]
The issue was in the `migrations/2_deploy_contracts.js`. He had added another block of code to deploy his millionaires problem secret contract, but it was outside the definition of the async deploy function block.

Once moved inside the block, the `discovery migrate` issue was resolved.

The original error on `discovery migrate` was `Syntax error: await is only valid in async function`.

**Comment by lauracw100** [comment]
Also had issues with the port (3333) and the missing set task key pair call in the migration and test scripts, and the client's utils/getEnigmaInit.js.
